// <auto-generated />
namespace curso.WebApiMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class creotablascontrol : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(creotablascontrol));
        
        string IMigrationMetadata.Id
        {
            get { return "201910252020243_creo tablas control"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
